### ISSUE TITLE
java error when using the new version of Fatjar : RiseClipseValidatorSCL-1.1.0-a22.jar

### ISSUE THREAD

**Issue by ADehouck** [riseclipse/riseclipse-validator-scl2003#13]
Command line used : 
java -jar RiseClipseValidatorSCL-1.1.0-a22.jar --make-explicit-links file.scd SCL_OCL

Raise the error bellow (with any SCL file as Input)

ERROR:   unknown feature projectDescription in object DocumentRoot (defined at line 2)
ERROR:   unknown feature name in object DocumentRoot (defined at line 3)
ERROR:   unknown feature comment in object DocumentRoot (defined at line 4)
ERROR:   unknown feature projects in object DocumentRoot (defined at line 5)
ERROR:   unknown feature buildSpec in object DocumentRoot (defined at line 7)
ERROR:   unknown feature natures in object DocumentRoot (defined at line 9)
Exception in thread "main" java.lang.ClassCastException: org.eclipse.emf.ecore.xml.type.impl.XMLTypeDocumentRootImpl cannot be cast to fr.centralesupelec.edf.riseclipse.iec61850.scl.SCL
        at fr.centralesupelec.edf.riseclipse.iec61850.scl.util.SclResourceSetImpl.buildExplicitLinks(SclResourceSetImpl.java:73)
        at fr.centralesupelec.edf.riseclipse.iec61850.scl.util.SclResourceSetImpl.finalizeLoad(SclResourceSetImpl.java:66)
        at fr.centralesupelec.edf.riseclipse.util.AbstractRiseClipseModelLoader.finalizeLoad(AbstractRiseClipseModelLoader.java:140)
        at fr.centralesupelec.edf.riseclipse.iec61850.scl.validator.RiseClipseValidatorSCL.run(RiseClipseValidatorSCL.java:570)
        at fr.centralesupelec.edf.riseclipse.iec61850.scl.validator.RiseClipseValidatorSCL.main(RiseClipseValidatorSCL.java:372)

**Comment by ADehouck** [comment]
It seams to be because the Zip package available for download contains a file : ".project" that causes this error

https://github.com/riseclipse/riseclipse.github.io/blob/master/downloads/SCL_OCL.zip
